name: test tj-glob

on:
  workflow_dispatch

jobs:
  run-glob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - uses: tj-actions/glob@v20
      with:
        files: '*.md'
