name: YAMLlint

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.yml'
      - '**.yaml'
  push:
    branches:
      - main
    paths:
      - '**.yml'
      - '**.yaml'

run-name: Run linter on YAML files
jobs:
  Yamllint:
    name: GitHub YAMLlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
